(function(){
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const DATA=window.GAAISO_DATA||{}; const IG=DATA.instagram||'https://www.instagram.com/gaaiso/';
  const LS={notes:'gaaiso_notes_v1', gallery:'gaaiso_gallery_v1', products:'gaaiso_products_v1'};
  function merged(key){try{const v=JSON.parse(localStorage.getItem(LS[key])||'[]');return [...(DATA[key]||[]),...v]}catch{return DATA[key]||[]}}
  function toast(msg){let t=$('.toast'); if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)} t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
  function nav(){const h=$('.hamb'),m=$('.mobile-menu'); if(h&&m){h.addEventListener('click',()=>m.classList.toggle('open')); m.addEventListener('click',e=>{if(e.target.tagName==='A')m.classList.remove('open')})} $$('[data-instagram]').forEach(a=>a.href=IG)}
  function footer(){const c=DATA.contact||{}; $$('[data-address]').forEach(e=>e.textContent=c.address||'Imphal, Manipur, India'); $$('[data-phone]').forEach(e=>e.textContent=c.phone||'+91 XXXXX XXXXX'); $$('[data-email]').forEach(e=>e.textContent=c.email||'hello@gaaiso.com'); $$('[data-hours]').forEach(e=>e.textContent=c.hours||'10:00 AM – 5:00 PM')}
  function hero(){const stage=$('#heroStage'),frame=$('#photoFrame'),dots=$('#dots'); if(!stage||!frame||!dots)return; const items=DATA.hero||[]; frame.innerHTML=items.map((x,i)=>`<div class="slide ${i===0?'active':''}"><img src="${x.src}" alt="${x.title} ${x.text}"><div class="caption"><b>${x.title}</b><span>${x.text}</span></div></div>`).join(''); let current=0,timer,startX=0; items.forEach((_,i)=>{const b=document.createElement('button');b.className='dot'+(i===0?' active':'');b.setAttribute('aria-label','Go to photo '+(i+1));b.onclick=()=>go(i,true);dots.appendChild(b)}); const slides=$$('.slide',frame), dotEls=$$('.dot',dots); function go(i,manual=false){slides[current]?.classList.remove('active');dotEls[current]?.classList.remove('active');current=(i+slides.length)%slides.length;slides[current]?.classList.add('active');dotEls[current]?.classList.add('active');frame.style.transform=`rotate(${current%2?'.55':'-.55'}deg)`; if(manual)restart()} function nextRandom(){let n;if(slides.length<2)return;do{n=Math.floor(Math.random()*slides.length)}while(n===current);go(n)} function restart(){clearInterval(timer);timer=setInterval(nextRandom,3000)} frame.addEventListener('pointerdown',e=>{startX=e.clientX;clearInterval(timer)},{passive:true}); frame.addEventListener('pointerup',e=>{const dx=e.clientX-startX;if(Math.abs(dx)>38)go(current+(dx<0?1:-1),true);else restart()},{passive:true}); restart();}
  function lightbox(){let lb=$('.lightbox'); if(!lb){lb=document.createElement('div');lb.className='lightbox';lb.innerHTML='<div class="lightbox-card"><button class="close" aria-label="Close">×</button><div class="lightbox-img"><img alt=""></div><div class="lightbox-text"><b></b><span></span></div></div>';document.body.appendChild(lb)} const img=$('.lightbox img'),b=$('.lightbox b'),s=$('.lightbox span'); lb.addEventListener('click',e=>{if(e.target===lb||e.target.className==='close')lb.classList.remove('open')}); document.addEventListener('keydown',e=>{if(e.key==='Escape')lb.classList.remove('open')}); return {open:(src,title,cat)=>{img.src=src;b.textContent=title;s.textContent=cat||'';lb.classList.add('open')}}}
  function renderGallery(){const root=$('#galleryGrid'); if(!root)return; const items=merged('gallery'); const cats=['All',...new Set(items.map(i=>i.category).filter(Boolean))]; const filters=$('#galleryFilters'); let active='All'; const lb=lightbox(); function draw(){root.innerHTML=items.filter(i=>active==='All'||i.category===active).map(i=>`<figure data-src="${i.src}" data-title="${i.title}" data-cat="${i.category||''}"><img src="${i.src}" alt="${i.title}"><figcaption>${i.title}</figcaption></figure>`).join(''); $$('figure',root).forEach(f=>f.onclick=()=>lb.open(f.dataset.src,f.dataset.title,f.dataset.cat))} if(filters){filters.innerHTML=cats.map(c=>`<button class="filter ${c===active?'active':''}" data-cat="${c}">${c}</button>`).join(''); filters.onclick=e=>{if(e.target.matches('.filter')){active=e.target.dataset.cat;$$('.filter',filters).forEach(x=>x.classList.toggle('active',x.dataset.cat===active));draw()}}} draw();}
  function renderProducts(){const root=$('#productGrid'); if(!root)return; root.innerHTML=merged('products').map(p=>`<article class="product"><div class="product-img"><img src="${p.src}" alt="${p.name}"></div><div class="product-body"><span class="status">${p.status||'Available'}</span><h3>${p.name}</h3><p>${p.tag||''}</p><p><strong>${p.price||'Price on request'}</strong></p><a class="btn dark full" href="${IG}" target="_blank" rel="noopener">Enquire on Instagram</a></div></article>`).join('')}
  function guestbook(){const list=$('#guestList'),form=$('#guestForm'); if(!list&&!form)return; function notes(){return merged('notes')} function draw(){if(list)list.innerHTML=notes().map(n=>`<div class="note"><b>${n.name}</b><p>${n.message}</p><span>${n.city||'Guest'}</span></div>`).join('')} draw(); if(form)form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const n={name:fd.get('name')||'Guest',city:fd.get('city')||'',message:fd.get('message')||''}; if(!n.message.trim())return toast('Please write a message.'); const arr=JSON.parse(localStorage.getItem(LS.notes)||'[]');arr.unshift(n);localStorage.setItem(LS.notes,JSON.stringify(arr));form.reset();draw();toast('Guest book message saved on this device.')})}
  function enquiry(){const f=$('#enquiryForm'); if(!f)return; f.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(f);const msg=`Hello GAAISO, I am interested in ${fd.get('product')||'your collection'}. Name: ${fd.get('name')||''}. Phone/Email: ${fd.get('contact')||''}. Message: ${fd.get('message')||''}`; window.open(IG+'?text='+encodeURIComponent(msg),'_blank'); toast('Opening Instagram for enquiry.')})}
  document.addEventListener('DOMContentLoaded',()=>{nav();footer();hero();renderGallery();renderProducts();guestbook();enquiry();});
})();
