(function(){
  const PASSWORD='AV123';
  const DATA=window.GAAISO_DATA||{};
  const LS={login:'gaaiso_admin_login_v2',home:'gaaiso_homepage_v2',design:'gaaiso_design_v2',hero:'gaaiso_hero_media_v2',video:'gaaiso_video_v2',galleryFull:'gaaiso_gallery_full_v2',productsFull:'gaaiso_products_full_v2',notes:'gaaiso_notes_v1'};
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const fallbackHome={eyebrow:'Locally made · Naturally unique',heroTitle:'Handcrafted gifts from Imphal.',heroSubtitle:'A calm boutique website for GAAISO’s jewellery, curated hampers and handmade pieces — designed like a soft paper gallery for visitors from Manipur and the world.',primaryButton:'View Gallery',secondaryButton:'Shop / Enquire',miniNote:'Swipe the torn-paper photo hero. The photos auto-change quickly and stay clean on mobile screens.',aboutTitle:'A calm boutique for curated gifting.',aboutText:'GAAISO is a handcrafted lifestyle and gifting brand from Imphal, bringing together jewellery, hampers and naturally styled pieces with a soft, personal touch.',aboutSecondText:'The page is designed to feel original, warm and photo-first — perfect for Instagram visitors and international discovery.',footerBio:'Handcrafted jewellery, hampers and curated gifts from Imphal. A quiet photo-first space for craft, gifting and discovery.',contact:{address:'Imphal, Manipur, India',phone:'+91 XXXXX XXXXX',email:'hello@gaaiso.com',hours:'10:00 AM – 5:00 PM'}};
  const fallbackDesign={fontFamily:'inter',primaryColor:'#8b6f4e',secondaryColor:'#a89f8b',backgroundColor:'#f7f3ee',cardColor:'#fffdf9',inkColor:'#12120f',buttonColor:'#6f7040',logoText:'GAAISO',logoImage:''};
  function read(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):structuredClone(fallback)}catch{return structuredClone(fallback)}}
  function write(key,val){localStorage.setItem(key,JSON.stringify(val));localStorage.setItem('gaaiso_last_saved',new Date().toLocaleString());renderLastSaved()}
  function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
  function fileToDataURL(file,maxMB=4.5){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(file.size>maxMB*1024*1024)return reject(new Error('File is too large for browser storage. Use an assets/ path or compress it below '+maxMB+' MB.'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Could not read file'));r.readAsDataURL(file)})}
  function getHome(){return read(LS.home,fallbackHome)}
  function getDesign(){return read(LS.design,fallbackDesign)}
  function getHero(){const saved=read(LS.hero,null);return Array.isArray(saved)&&saved.length?saved:structuredClone(DATA.hero||[]).map(x=>({...x,active:true}))}
  function getVideo(){return read(LS.video,{enabled:false,label:'Watch GAAISO Story',src:''})}
  function getGallery(){const saved=read(LS.galleryFull,null);return Array.isArray(saved)?saved:structuredClone(DATA.gallery||[])}
  function getProducts(){const saved=read(LS.productsFull,null);return Array.isArray(saved)?saved:structuredClone(DATA.products||[])}
  function getNotes(){return read(LS.notes,[])}
  function showApp(){ $('#loginScreen').classList.add('hidden'); $('#adminStudio').classList.remove('hidden'); renderAll(); }
  function renderLastSaved(){const v=localStorage.getItem('gaaiso_last_saved'); $$('#lastSaved').forEach(x=>x.textContent='Last saved: '+(v||'not yet'))}
  function setTab(name){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name)); $$('.tab-page').forEach(p=>p.classList.toggle('active',p.id==='tab-'+name)); document.querySelector('.sidebar')?.classList.remove('open')}
  function editorHTML(){const h=getHome();return `<h2>Homepage Text Editor</h2><p>Edit text content that appears on your homepage.</p>
    ${field('Eyebrow','eyebrow',h.eyebrow,80)}${field('Hero Title','heroTitle',h.heroTitle,100)}${area('Hero Subtitle','heroSubtitle',h.heroSubtitle,180)}
    <div class="form-row">${field('Primary Button Text','primaryButton',h.primaryButton,30)}${field('Secondary Button Text','secondaryButton',h.secondaryButton,30)}</div>
    ${area('Hero Mini Note','miniNote',h.miniNote,180)}${field('About Title','aboutTitle',h.aboutTitle,100)}${area('About Section Text','aboutText',h.aboutText,300)}${area('About Second Paragraph','aboutSecondText',h.aboutSecondText,300)}${area('Footer Brand Text','footerBio',h.footerBio,240)}
    <h3>Footer Contact</h3><div class="form-row"><div class="field"><label>Address</label><input class="input home-contact" data-contact="address" value="${esc(h.contact.address)}"></div><div class="field"><label>Phone</label><input class="input home-contact" data-contact="phone" value="${esc(h.contact.phone)}"></div></div><div class="form-row"><div class="field"><label>Email</label><input class="input home-contact" data-contact="email" value="${esc(h.contact.email)}"></div><div class="field"><label>Hours</label><input class="input home-contact" data-contact="hours" value="${esc(h.contact.hours)}"></div></div>
    <div class="save-row"><button class="save-btn" id="saveHome">▣ Save Homepage Text</button></div>`}
  function field(label,key,value,max){return `<div class="field"><label>${label}<small>${String(value||'').length} / ${max}</small></label><div class="toolbar"><span>H</span><span>B</span><span>I</span><span>U</span><span>≡</span><span>↗</span></div><input class="input rich-input home-field" data-key="${key}" maxlength="${max}" value="${esc(value)}"></div>`}
  function area(label,key,value,max){return `<div class="field"><label>${label}<small>${String(value||'').length} / ${max}</small></label><div class="toolbar"><span>¶</span><span>B</span><span>I</span><span>U</span><span>•</span><span>↗</span></div><textarea class="textarea rich-input home-field" data-key="${key}" maxlength="${max}">${esc(value)}</textarea></div>`}
  function heroHTML(){const hero=getHero(),video=getVideo();return `<h2>Hero Media Manager</h2><p>Manage hero images and optional video for the homepage.</p><div class="save-row" style="justify-content:flex-end;margin-top:0"><button class="ghost-btn" id="addHeroPath">+ Add Image Path</button><label class="ghost-btn">+ Upload Images<input id="heroFile" type="file" accept="image/*" multiple hidden></label></div><div class="media-list" id="heroList">${hero.map((x,i)=>mediaRow(x,i)).join('')}</div><small class="item-meta" style="display:block;text-align:center;margin:10px 0 0">Use ↑ ↓ to reorder. Toggle active/inactive without deleting.</small><div class="toggle-row"><b>Show Video Button</b><label class="switch"><input id="videoEnabled" type="checkbox" ${video.enabled?'checked':''}><span class="slider"></span></label></div><div class="field"><label>Video Button Text <small>${(video.label||'').length} / 30</small></label><input id="videoLabel" class="input" maxlength="30" value="${esc(video.label||'Watch GAAISO Story')}"></div><div class="field"><label>MP4 / Video URL or asset path</label><input id="videoSrc" class="input" placeholder="assets/gaaiso-story.mp4 or https://..." value="${esc(video.src||'')}"></div><div class="field"><label>Upload MP4 Video <small>small files only for local storage</small></label><input id="videoFile" class="upload-box" type="file" accept="video/mp4,video/webm,video/ogg,video/*"></div><div class="save-row"><button class="ghost-btn" id="previewVideo">▶ Preview Video</button><button class="save-btn" id="saveHero">▣ Save Hero Media</button></div>`}
  function mediaRow(x,i){return `<div class="media-item" data-i="${i}"><div class="media-thumb"><img src="${esc(x.src)}" alt=""></div><div><input class="input hero-title" value="${esc(x.title||'')}" placeholder="Image title"><input class="input hero-text" value="${esc(x.text||'')}" placeholder="Caption" style="margin-top:6px"><span class="badge">${x.active===false?'Inactive':'Active'}</span></div><div class="row-actions"><button class="icon-btn hero-up">↑</button><button class="icon-btn hero-down">↓</button><button class="icon-btn hero-toggle">${x.active===false?'✓':'○'}</button><button class="icon-btn hero-del">🗑</button></div></div>`}
  function previewHTML(){const h=getHome(),d=getDesign(),hero=getHero().filter(x=>x.active!==false),v=getVideo(),img=(hero[0]||{}).src||'../assets/gaaiso-11.jpg';return `<h2>Live Preview</h2><p>See how your homepage looks.</p><div class="device-buttons"><button>▣</button><button>▯</button><button>▯</button></div><div class="preview-card" style="background:${esc(d.buttonColor)}"><img src="${esc(img)}" alt=""><div class="preview-content"><h1>${esc(h.heroTitle)}</h1><p>${esc(h.heroSubtitle)}</p><div class="preview-actions"><span>${esc(h.primaryButton)}</span><span>${esc(h.secondaryButton)}</span>${v.enabled?`<span>▶ ${esc(v.label)}</span>`:''}</div></div><div class="preview-dots"><i></i><i></i><i></i><i></i></div></div>`}
  function galleryHTML(full=false){const g=getGallery();return `<h2>Gallery Manager${full?'':' <small>(Quick View)</small>'}</h2><p>Manage all gallery photos. New uploads are added to the existing gallery list.</p>${full?`<div class="add-form"><input id="galleryTitle" class="input" placeholder="Photo title"><input id="galleryCategory" class="input" placeholder="Category"><input id="galleryPath" class="input" placeholder="assets/photo.jpg"><label class="ghost-btn">Upload Photo<input id="galleryFile" type="file" accept="image/*" hidden></label></div><div class="save-row"><button class="save-btn" id="addGallery">+ Add Photo</button><button class="ghost-btn" id="saveGallery">Save Gallery</button></div><div class="gallery-grid-admin" id="galleryAdminGrid">${g.map((x,i)=>galleryCard(x,i)).join('')}</div>`:`<div class="gallery-strip">${g.slice(0,4).map(x=>`<div class="gallery-mini"><img src="${esc(x.src)}"></div>`).join('')}<div class="add-tile">+${Math.max(g.length-4,0)}<br>More Photos</div></div><small>Total Photos: ${g.length}</small>`}`}
  function galleryCard(x,i){return `<div class="gallery-admin-card" data-i="${i}"><div class="img"><img src="${esc(x.src)}"></div><div class="body"><input class="input gal-title" value="${esc(x.title||'')}" placeholder="Title"><input class="input gal-cat" value="${esc(x.category||'')}" placeholder="Category"><input class="input gal-src" value="${esc(x.src||'')}" placeholder="Image source"><div class="row-actions"><button class="icon-btn gal-up">↑</button><button class="icon-btn gal-down">↓</button><button class="icon-btn gal-del">🗑</button></div></div></div>`}
  function shopHTML(full=false){const p=getProducts();return `<h2>Shop Manager${full?'':' <small>(Quick View)</small>'}</h2><p>Manage catalogue products and enquiry items.</p>${full?`<div class="add-form"><input id="prodName" class="input" placeholder="Product name"><input id="prodPrice" class="input" placeholder="Price"><input id="prodTag" class="input" placeholder="Short tag"><input id="prodStatus" class="input" placeholder="Available / Custom order"><input id="prodPath" class="input" placeholder="assets/product.jpg"><label class="ghost-btn">Upload Photo<input id="prodFile" type="file" accept="image/*" hidden></label></div><div class="save-row"><button class="save-btn" id="addProduct">+ Add Product</button><button class="ghost-btn" id="saveProducts">Save Products</button></div><div class="shop-list" id="productAdminList">${p.map((x,i)=>productRow(x,i,true)).join('')}</div>`:`<div class="shop-list">${p.slice(0,4).map((x,i)=>productRow(x,i,false)).join('')}</div><small>View All Products →</small>`}`}
  function productRow(x,i,edit){return `<div class="product-row" data-i="${i}"><div class="product-thumb"><img src="${esc(x.src)}"></div><div>${edit?`<input class="input prod-name" value="${esc(x.name||'')}" placeholder="Name"><div class="form-row" style="margin-top:6px"><input class="input prod-price" value="${esc(x.price||'')}" placeholder="Price"><input class="input prod-status" value="${esc(x.status||'')}" placeholder="Status"></div><input class="input prod-tag" value="${esc(x.tag||'')}" placeholder="Tag" style="margin-top:6px"><input class="input prod-src" value="${esc(x.src||'')}" placeholder="Image source" style="margin-top:6px">`:`<b>${esc(x.name)}</b><span class="item-meta">${esc(x.price||'Price on request')}</span>`}</div><div class="row-actions">${edit?'<button class="icon-btn prod-up">↑</button><button class="icon-btn prod-down">↓</button><button class="icon-btn prod-del">🗑</button>':'<button class="icon-btn">✎</button><button class="icon-btn">🗑</button>'}</div></div>`}
  function designHTML(){const d=getDesign();return `<h2>Design & Branding</h2><p>Customize the look and feel of your website.</p><div class="design-grid"><div>${selectField('Font Family','fontFamily',d.fontFamily,[['inter','Japandi Sans'],['serif','Boutique Serif'],['system','Modern System']])}<div class="field"><label>Logo Text</label><input id="logoText" class="input" value="${esc(d.logoText)}"></div><div class="form-row"><div class="field"><label>Primary Color</label><div class="color-field"><input type="color" id="primaryColor" value="${esc(d.primaryColor)}"><input class="input" id="primaryColorText" value="${esc(d.primaryColor)}"></div></div><div class="field"><label>Secondary Color</label><div class="color-field"><input type="color" id="secondaryColor" value="${esc(d.secondaryColor)}"><input class="input" id="secondaryColorText" value="${esc(d.secondaryColor)}"></div></div></div><div class="form-row"><div class="field"><label>Background</label><div class="color-field"><input type="color" id="backgroundColor" value="${esc(d.backgroundColor)}"><input class="input" id="backgroundColorText" value="${esc(d.backgroundColor)}"></div></div><div class="field"><label>Button Color</label><div class="color-field"><input type="color" id="buttonColor" value="${esc(d.buttonColor)}"><input class="input" id="buttonColorText" value="${esc(d.buttonColor)}"></div></div></div></div><div><label>Logo</label><div class="logo-preview" id="logoPreview">${d.logoImage?`<img src="${esc(d.logoImage)}">`:`<span>${esc(d.logoText)}</span>`}</div><div class="save-row"><label class="ghost-btn">Change Logo<input id="logoFile" type="file" accept="image/*" hidden></label><button class="danger-btn" id="removeLogo">Remove</button></div></div></div><div class="save-row"><button class="save-btn" id="saveDesign">⚙ Save Design Settings</button></div>`}
  function selectField(label,key,value,opts){return `<div class="field"><label>${label}</label><select class="select" id="${key}">${opts.map(([v,t])=>`<option value="${v}" ${v===value?'selected':''}>${t}</option>`).join('')}</select></div>`}
  function guestHTML(full=false){const notes=getNotes();const total=notes.length, approved=notes.filter(n=>n.status==='approved'||!n.status).length,pending=notes.filter(n=>n.status==='pending').length,spam=notes.filter(n=>n.status==='spam').length;return `<h2>Guest Book Manager${full?'':' <small>(Quick View)</small>'}</h2><p>Manage messages from visitors.</p><div class="stats"><div class="stat"><b>${total}</b><span>Total</span></div><div class="stat"><b>${approved}</b><span>Approved</span></div><div class="stat"><b>${pending}</b><span>Pending</span></div><div class="stat"><b>${spam}</b><span>Spam</span></div></div>${full?`<div class="notes-list" style="margin-top:16px">${notes.length?notes.map((n,i)=>noteRow(n,i)).join(''):'<p>No local guest messages yet.</p>'}</div>`:`<div style="margin-top:16px">${notes.slice(0,3).map((n,i)=>noteRow(n,i)).join('')||'<p>No local guest messages yet.</p>'}</div><small>View All Messages →</small>`}`}
  function noteRow(n,i){return `<div class="note-row" data-i="${i}"><div><b>${esc(n.name||'Guest')}</b><p>${esc(n.message||'')}</p><span class="item-meta">${esc(n.city||'')} · ${esc(n.status||'approved')}</span></div><div class="row-actions"><button class="icon-btn note-approve">✓</button><button class="icon-btn note-spam">!</button><button class="icon-btn note-del">🗑</button></div></div>`}
  function backupHTML(){return `<h2>Backup & Restore</h2><p>Export or import all admin edits. This is useful before pushing permanent changes later.</p><div class="save-row" style="justify-content:flex-start"><button class="save-btn" id="refreshExport">Refresh Export</button><button class="ghost-btn" id="downloadExport">Download JSON</button><label class="ghost-btn">Import JSON<input id="importFile" type="file" accept="application/json" hidden></label><button class="danger-btn" id="resetAdmin">Reset Admin Edits</button></div><pre class="backup-box" id="exportBox"></pre>`}
  function renderAll(){
    $$('.editor-panel').forEach(el=>el.innerHTML=editorHTML()); $$('.hero-panel').forEach(el=>el.innerHTML=heroHTML()); $$('.preview-panel').forEach(el=>el.innerHTML=previewHTML()); $$('.gallery-panel').forEach(el=>el.innerHTML=galleryHTML(false)); $('.gallery-full-panel').innerHTML=galleryHTML(true); $$('.shop-panel').forEach(el=>el.innerHTML=shopHTML(false)); $('.shop-full-panel').innerHTML=shopHTML(true); $('.design-panel').innerHTML=designHTML(); $$('.guest-panel').forEach(el=>el.innerHTML=guestHTML(false)); $('.guest-full-panel').innerHTML=guestHTML(true); $('.backup-panel').innerHTML=backupHTML(); renderLastSaved(); bindDynamic(); updateExport();
  }
  function collectHome(){const h=getHome(); $$('.home-field').forEach(i=>h[i.dataset.key]=i.value); $$('.home-contact').forEach(i=>{h.contact=h.contact||{};h.contact[i.dataset.contact]=i.value}); return h}
  function collectHeroFromPanel(panel=document){return $$('.media-item',panel).map(row=>({src:getHero()[+row.dataset.i]?.src||'',title:$('.hero-title',row)?.value||'',text:$('.hero-text',row)?.value||'',active:!($('.badge',row)?.textContent||'').includes('Inactive')}))}
  function collectGalleryFromPanel(panel=document){return $$('.gallery-admin-card',panel).map(card=>({src:$('.gal-src',card).value,title:$('.gal-title',card).value,category:$('.gal-cat',card).value}))}
  function collectProductsFromPanel(panel=document){return $$('.product-row',panel).filter(r=>$('.prod-name',r)).map(row=>({src:$('.prod-src',row).value,name:$('.prod-name',row).value,price:$('.prod-price',row).value,tag:$('.prod-tag',row).value,status:$('.prod-status',row).value}))}
  function bindDynamic(){
    $$('#saveHome').forEach(b=>b.onclick=()=>{write(LS.home,collectHome());toast('Homepage text saved');renderAll()});
    $$('#saveHero').forEach(b=>b.onclick=()=>{const hero=collectHeroFromPanel(b.closest('.panel'));const v=getVideo();v.enabled=$('#videoEnabled',b.closest('.panel')).checked;v.label=$('#videoLabel',b.closest('.panel')).value;v.src=$('#videoSrc',b.closest('.panel')).value;write(LS.hero,hero);write(LS.video,v);toast('Hero media saved');renderAll()});
    $$('#addHeroPath').forEach(b=>b.onclick=()=>{const hero=getHero();hero.push({src:'assets/gaaiso-22.jpg',title:'New Hero Image',text:'Add caption here',active:true});write(LS.hero,hero);renderAll();toast('Hero image row added')});
    $$('#heroFile').forEach(inp=>inp.onchange=async e=>{try{const hero=getHero();for(const file of e.target.files){hero.push({src:await fileToDataURL(file),title:file.name.replace(/\.[^.]+$/,''),text:'Uploaded hero image',active:true})}write(LS.hero,hero);renderAll();toast('Hero image uploaded')}catch(err){toast(err.message)}});
    $$('.hero-up,.hero-down,.hero-toggle,.hero-del').forEach(btn=>btn.onclick=e=>{const hero=getHero(),i=+btn.closest('.media-item').dataset.i;if(btn.classList.contains('hero-up')&&i>0)[hero[i-1],hero[i]]=[hero[i],hero[i-1]];if(btn.classList.contains('hero-down')&&i<hero.length-1)[hero[i+1],hero[i]]=[hero[i],hero[i+1]];if(btn.classList.contains('hero-toggle'))hero[i].active=hero[i].active===false; if(btn.classList.contains('hero-del'))hero.splice(i,1);write(LS.hero,hero);renderAll()});
    $$('#videoFile').forEach(inp=>inp.onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const panel=inp.closest('.panel');$('#videoSrc',panel).value=await fileToDataURL(f,4);toast('Video uploaded locally. Save Hero Media.')}catch(err){toast(err.message)}});
    $$('#previewVideo').forEach(b=>b.onclick=()=>{const panel=b.closest('.panel');const src=$('#videoSrc',panel).value;if(!src)return toast('Add a video first');const m=$('#videoPreviewModal');$('video',m).src=src;m.classList.add('open')});
    $$('.modal-close').forEach(b=>b.onclick=()=>{const m=b.closest('.modal');$('video',m)?.pause();m.classList.remove('open')});
    $$('#addGallery').forEach(b=>b.onclick=async()=>{try{let src=$('#galleryPath').value;const file=$('#galleryFile').files[0];if(file)src=await fileToDataURL(file);if(!src)return toast('Add image path or upload photo');const g=getGallery();g.unshift({src,title:$('#galleryTitle').value||'New Gallery Photo',category:$('#galleryCategory').value||'Gallery'});write(LS.galleryFull,g);renderAll();toast('Gallery photo added')}catch(err){toast(err.message)}});
    $$('#saveGallery').forEach(b=>b.onclick=()=>{write(LS.galleryFull,collectGalleryFromPanel());toast('Gallery saved');renderAll()});
    $$('.gal-up,.gal-down,.gal-del').forEach(btn=>btn.onclick=()=>{const g=getGallery(),i=+btn.closest('.gallery-admin-card').dataset.i;if(btn.classList.contains('gal-up')&&i>0)[g[i-1],g[i]]=[g[i],g[i-1]];if(btn.classList.contains('gal-down')&&i<g.length-1)[g[i+1],g[i]]=[g[i],g[i+1]];if(btn.classList.contains('gal-del'))g.splice(i,1);write(LS.galleryFull,g);renderAll()});
    $$('#addProduct').forEach(b=>b.onclick=async()=>{try{let src=$('#prodPath').value;const file=$('#prodFile').files[0];if(file)src=await fileToDataURL(file);if(!src)return toast('Add product image path or upload photo');const p=getProducts();p.unshift({src,name:$('#prodName').value||'New Product',price:$('#prodPrice').value||'Price on request',tag:$('#prodTag').value||'',status:$('#prodStatus').value||'Available'});write(LS.productsFull,p);renderAll();toast('Product added')}catch(err){toast(err.message)}});
    $$('#saveProducts').forEach(b=>b.onclick=()=>{write(LS.productsFull,collectProductsFromPanel());toast('Products saved');renderAll()});
    $$('.prod-up,.prod-down,.prod-del').forEach(btn=>btn.onclick=()=>{const p=getProducts(),i=+btn.closest('.product-row').dataset.i;if(btn.classList.contains('prod-up')&&i>0)[p[i-1],p[i]]=[p[i],p[i-1]];if(btn.classList.contains('prod-down')&&i<p.length-1)[p[i+1],p[i]]=[p[i],p[i+1]];if(btn.classList.contains('prod-del'))p.splice(i,1);write(LS.productsFull,p);renderAll()});
    $$('#saveDesign').forEach(b=>b.onclick=()=>{const d=getDesign();['fontFamily','logoText','primaryColor','secondaryColor','backgroundColor','buttonColor'].forEach(k=>{const el=$('#'+k);if(el)d[k]=el.value});d.primaryColor=$('#primaryColorText')?.value||d.primaryColor;d.secondaryColor=$('#secondaryColorText')?.value||d.secondaryColor;d.backgroundColor=$('#backgroundColorText')?.value||d.backgroundColor;d.buttonColor=$('#buttonColorText')?.value||d.buttonColor;write(LS.design,d);toast('Design saved');renderAll()});
    ['primaryColor','secondaryColor','backgroundColor','buttonColor'].forEach(k=>{const c=$('#'+k),t=$('#'+k+'Text');if(c&&t){c.oninput=()=>t.value=c.value;t.oninput=()=>c.value=t.value}});
    const logoFile=$('#logoFile'); if(logoFile)logoFile.onchange=async e=>{try{const d=getDesign();d.logoImage=await fileToDataURL(e.target.files[0]);write(LS.design,d);renderAll();toast('Logo uploaded')}catch(err){toast(err.message)}}; const remove=$('#removeLogo'); if(remove)remove.onclick=()=>{const d=getDesign();d.logoImage='';write(LS.design,d);renderAll()};
    $$('.note-approve,.note-spam,.note-del').forEach(btn=>btn.onclick=()=>{const notes=getNotes(),i=+btn.closest('.note-row').dataset.i;if(btn.classList.contains('note-approve'))notes[i].status='approved';if(btn.classList.contains('note-spam'))notes[i].status='spam';if(btn.classList.contains('note-del'))notes.splice(i,1);write(LS.notes,notes);renderAll()});
    const refresh=$('#refreshExport'); if(refresh)refresh.onclick=updateExport; const dl=$('#downloadExport'); if(dl)dl.onclick=downloadExport; const imp=$('#importFile'); if(imp)imp.onchange=importExport; const reset=$('#resetAdmin'); if(reset)reset.onclick=()=>{if(confirm('Reset all admin edits stored in this browser?')){Object.values(LS).forEach(k=>{if(k!==LS.login)localStorage.removeItem(k)});localStorage.removeItem('gaaiso_last_saved');renderAll();toast('Admin edits reset')}};
  }
  function updateExport(){const box=$('#exportBox'); if(!box)return; const data={home:getHome(),design:getDesign(),hero:getHero(),video:getVideo(),gallery:getGallery(),products:getProducts(),notes:getNotes(),exportedAt:new Date().toISOString()};box.textContent=JSON.stringify(data,null,2)}
  function downloadExport(){updateExport();const blob=new Blob([$('#exportBox').textContent],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='gaaiso-admin-export.json';a.click();URL.revokeObjectURL(a.href)}
  async function importExport(e){try{const file=e.target.files[0];if(!file)return;const data=JSON.parse(await file.text());if(data.home)write(LS.home,data.home);if(data.design)write(LS.design,data.design);if(data.hero)write(LS.hero,data.hero);if(data.video)write(LS.video,data.video);if(data.gallery)write(LS.galleryFull,data.gallery);if(data.products)write(LS.productsFull,data.products);if(data.notes)write(LS.notes,data.notes);renderAll();toast('Backup imported')}catch(err){toast('Import failed: '+err.message)}}
  $('#loginForm').onsubmit=e=>{e.preventDefault();if($('#adminPassword').value===PASSWORD){localStorage.setItem(LS.login,'1');showApp()}else toast('Wrong password')};
  if(localStorage.getItem(LS.login)==='1')showApp();
  $$('#logoutBtn').forEach(b=>b.onclick=()=>{localStorage.removeItem(LS.login);location.reload()});
  document.addEventListener('click',e=>{const t=e.target.closest('[data-tab]');if(t)setTab(t.dataset.tab);const jump=e.target.closest('[data-jump]');if(jump)setTab(jump.dataset.jump)});
  $('#menuToggle').onclick=()=>$('.sidebar').classList.toggle('open');
})();
