(function(){
  const DATA=window.GAAISO_DATA||{}; const LS='gaaiso_products_full_v2';
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const categories=(DATA.commerce&&DATA.commerce.categories)||['All','Jewellery','Earrings','Bracelets','Hampers','Bouquets','Gift Sets','Handmade Crafts','Custom Orders'];
  function esc(v){return String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
  function read(){try{const saved=JSON.parse(localStorage.getItem(LS)||'null');if(Array.isArray(saved)&&saved.length)return saved}catch{} return structuredClone(DATA.products||[])}
  function write(items){localStorage.setItem(LS,JSON.stringify(items));localStorage.setItem('gaaiso_last_saved',new Date().toLocaleString())}
  function toast(msg){let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
  function fileToDataURL(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');if(file.size>4.5*1024*1024)return reject(new Error('Image too large. Compress below 4.5 MB or use assets/photo.jpg.'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Could not read file'));r.readAsDataURL(file)})}
  function moneyToAmount(price){const n=String(price||'').replace(/[^0-9.]/g,'');return n?+n:0}
  function optionList(active){return categories.filter(c=>c!=='All').map(c=>`<option value="${esc(c)}" ${c===active?'selected':''}>${esc(c)}</option>`).join('')}
  function productRow(p,i){return `<article class="commerce-admin-row" data-i="${i}" data-hidden="${p.visible===false?'1':'0'}"><div class="thumb"><img src="${esc(p.src)}" alt=""></div><div class="commerce-admin-fields"><div class="form-row"><input class="input ca-name" value="${esc(p.name||'')}" placeholder="Product name"><select class="input ca-category">${optionList(p.category)}</select></div><div class="form-row"><input class="input ca-price" value="${esc(p.price||'')}" placeholder="₹ price"><input class="input ca-amount" value="${esc(p.amount||moneyToAmount(p.price))}" placeholder="Numeric amount"></div><div class="form-row"><input class="input ca-status" value="${esc(p.status||'Available')}" placeholder="Available / Sold / Custom order"><input class="input ca-delivery" value="${esc(p.delivery||'Delivery extra')}" placeholder="Delivery option"></div><input class="input ca-tag" value="${esc(p.tag||'')}" placeholder="Short sales note"><input class="input ca-note" value="${esc(p.deliveryNote||'Delivery or courier charges are extra unless mentioned.')}" placeholder="Delivery note"><div class="form-row"><input class="input ca-upi" value="${esc(p.upiId||(DATA.commerce&&DATA.commerce.upiId)||'gaaiso@upi')}" placeholder="UPI ID"><input class="input ca-src" value="${esc(p.src||'')}" placeholder="Image path"></div><div class="commerce-admin-actions"><button class="ca-up">↑</button><button class="ca-down">↓</button><button class="ca-hide">${p.visible===false?'Show':'Hide'}</button><button class="danger ca-del">Delete</button></div></div></article>`}
  function shell(){return `<div class="admin-commerce-board"><div><h2>Shop Manager</h2><p>Every website photo can become a product. Edit price, category, delivery, UPI ID and image. Changes save in this browser and can be exported from Backup.</p><div class="admin-pay-help"><b>Payment note:</b> UPI/GPay buttons use each product amount and UPI ID. Keep the UPI ID updated before launch. Delivery/courier charges are shown as notes and should be confirmed manually with the customer.</div></div><div class="add-form"><input id="caNewName" class="input" placeholder="Product name"><select id="caNewCategory" class="input">${optionList('Jewellery')}</select><input id="caNewPrice" class="input" placeholder="₹ price"><input id="caNewPath" class="input" placeholder="assets/photo.jpg"><label class="ghost-btn">Upload Photo<input id="caNewFile" type="file" accept="image/*" hidden></label></div><div class="save-row" style="justify-content:flex-start"><button class="save-btn" id="caAddProduct">+ Add Product</button><button class="ghost-btn" id="caSaveProducts">Save Product Catalogue</button><button class="ghost-btn" id="caResetProducts">Restore Default Products</button></div><div class="commerce-admin-grid" id="caProductList">${read().map(productRow).join('')}</div></div>`}
  function collect(root){return $$('.commerce-admin-row',root).map(row=>({id:'prod-'+Date.now()+'-'+row.dataset.i,src:$('.ca-src',row).value,name:$('.ca-name',row).value,category:$('.ca-category',row).value,price:$('.ca-price',row).value,amount:moneyToAmount($('.ca-amount',row).value||$('.ca-price',row).value),status:$('.ca-status',row).value,delivery:$('.ca-delivery',row).value,tag:$('.ca-tag',row).value,deliveryNote:$('.ca-note',row).value,upiId:$('.ca-upi',row).value,payeeName:(DATA.commerce&&DATA.commerce.payeeName)||'GAAISO',visible:row.dataset.hidden==='1'?false:true}))}
  function bind(panel){$('#caSaveProducts',panel).onclick=()=>{write(collect(panel));toast('Shop catalogue saved')};$('#caResetProducts',panel).onclick=()=>{if(confirm('Restore default product list?')){localStorage.removeItem(LS);install(true);toast('Default products restored')}};$('#caAddProduct',panel).onclick=async()=>{try{let src=$('#caNewPath',panel).value;const f=$('#caNewFile',panel).files[0];if(f)src=await fileToDataURL(f);if(!src)return toast('Add image path or upload photo');const items=collect(panel);items.unshift({id:'prod-'+Date.now(),src,name:$('#caNewName',panel).value||'New Product',category:$('#caNewCategory',panel).value,price:$('#caNewPrice',panel).value||'Price on request',amount:moneyToAmount($('#caNewPrice',panel).value),status:'Available',delivery:'Delivery extra',tag:'New item',deliveryNote:'Delivery or courier charges are extra unless mentioned.',upiId:(DATA.commerce&&DATA.commerce.upiId)||'gaaiso@upi',payeeName:'GAAISO'});write(items);install(true);toast('Product added')}catch(e){toast(e.message)}};$$('.ca-up,.ca-down,.ca-del,.ca-hide',panel).forEach(btn=>btn.onclick=()=>{const row=btn.closest('.commerce-admin-row');let items=collect(panel);const i=+row.dataset.i;if(btn.classList.contains('ca-up')&&i>0)[items[i-1],items[i]]=[items[i],items[i-1]];if(btn.classList.contains('ca-down')&&i<items.length-1)[items[i+1],items[i]]=[items[i],items[i+1]];if(btn.classList.contains('ca-del'))items.splice(i,1);if(btn.classList.contains('ca-hide'))items[i].visible=items[i].visible===false?true:false;write(items);install(true)})}
  function install(force=false){const panel=$('.shop-full-panel');if(!panel)return;if(panel.dataset.commerceEnhanced==='1'&&!force)return;panel.dataset.commerceEnhanced='1';panel.innerHTML=shell();bind(panel)}
  document.addEventListener('DOMContentLoaded',()=>{install();const obs=new MutationObserver(()=>install());obs.observe(document.body,{childList:true,subtree:true})});
})();
